# Generated by Django 5.1.4 on 2025-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('delivery_data', models.DateField(null=True)),
                ('delivery_forcast', models.DateField(null=True)),
                ('dimensions', models.CharField(max_length=100)),
                ('wieght', models.FloatField()),
                ('amout', models.FloatField()),
            ],
        ),
    ]
