# Generated by Django 5.1.4 on 2025-03-25 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_phone'),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('pickup_schedule', models.DateField()),
                ('zip_code', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=80)),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
                ('width', models.FloatField()),
                ('wieght', models.FloatField()),
                ('estimated_price', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dr_customer', to='customers.customer')),
            ],
        ),
    ]
